// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmXNnpHA9GX1wy7rzluu_aIVbfU9qGng',
    appId: '1:665785006335:android:e1c0ce84a35bec22eff4ca',
    messagingSenderId: '665785006335',
    projectId: 'note-app-70689',
    storageBucket: 'note-app-70689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNg8vcI6M4_R9xoi52KBuvJQnO8_6uUgQ',
    appId: '1:665785006335:ios:0760f724ccfdf66beff4ca',
    messagingSenderId: '665785006335',
    projectId: 'note-app-70689',
    storageBucket: 'note-app-70689.appspot.com',
    androidClientId: '665785006335-tpin176ua89j5rq5jvj7i9lf6k0ce5q6.apps.googleusercontent.com',
    iosClientId: '665785006335-a32j2bfga9i4ls94537om641csl576o6.apps.googleusercontent.com',
    iosBundleId: 'com.littlelarge.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNg8vcI6M4_R9xoi52KBuvJQnO8_6uUgQ',
    appId: '1:665785006335:ios:1b50748e8a1330b0eff4ca',
    messagingSenderId: '665785006335',
    projectId: 'note-app-70689',
    storageBucket: 'note-app-70689.appspot.com',
    androidClientId: '665785006335-tpin176ua89j5rq5jvj7i9lf6k0ce5q6.apps.googleusercontent.com',
    iosClientId: '665785006335-f05h10dv47vpagcrb7717q0pr510qr6k.apps.googleusercontent.com',
    iosBundleId: 'com.littlelarge.notes.RunnerTests',
  );
}
